import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {DEFAULT_RENDER_DISTANCE,UNDERWATER_RENDER_DISTANCE} from './config.js';
import {ITEMS} from './blocks.js';
import {createWorld} from './world.js';
import {createRenderer} from './rendering.js';
import {createChunkManager} from './chunks.js';
import {updateWaterView,isUnderwater} from './water.js';
import {createPlayer,savePlayer} from './player.js';
import {movePlayer,syncCamera} from './physics.js';
import {saveWorld,loadWorld,downloadSave,readImport} from './save.js';
import {renderHotbar,status} from './ui.js';
let scene,camera,renderer,world,player,chunks,raycaster,atlas;let locked=false,last=performance.now(),selected=0,underwater=false,keys=new Set(),velocity=new THREE.Vector3(),worldName='My World',autosave=0;const canvas=document.querySelector('#game');
const inventory={grass:64,dirt:64,stone:64,sand:32,wood:32,leaves:32,glass:16,water:16,coal:0,iron:0,planks:0,brick:0,glow:0};
function setupScene(){renderer=createRenderer(canvas);scene=new THREE.Scene();scene.background=new THREE.Color(0x79b9e8);scene.fog=new THREE.Fog(0x79b9e8,55,150);camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,220);scene.add(camera);raycaster=new THREE.Raycaster();raycaster.far=7;scene.add(new THREE.HemisphereLight(0xffffff,0x334455,1.6));const sun=new THREE.DirectionalLight(0xffffff,1.8);sun.position.set(30,70,20);scene.add(sun)}
async function loadTexture(){return new Promise((resolve,reject)=>new THREE.TextureLoader().load('./assets/block_atlas.png',t=>{t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.colorSpace=THREE.SRGBColorSpace;resolve(t)},undefined,reject))}
function initWorld(w,name){world=w;worldName=name||'My World';player=createPlayer(world);if(player.feetY<2)player.feetY=world.heightAt(Math.floor(player.x),Math.floor(world.player.z||0))+1.01;camera.rotation.order='YXZ';chunks?.dispose();chunks=createChunkManager(world,scene,atlas);const d=updateWaterView(scene,renderer,false);underwater=false;chunks.update(player.x,player.z,d);syncCamera(camera,player);status(`World ready · seed ${world.seed} · render ${d} chunks`);document.querySelector('#menu').classList.add('hidden')}
function pick(){raycaster.setFromCamera({x:0,y:0},camera);return raycaster.intersectObjects([...scene.children].filter(o=>o.isGroup),true)[0]||null}
function hitBlock(){const h=pick();if(!h)return null;const n=h.face?.normal;if(!n)return null;const p=h.point.clone().addScaledVector(n,-.01);return{x:Math.floor(p.x),y:Math.floor(p.y),z:Math.floor(p.z),n}}
function edit(breaking){const h=hitBlock();if(!h)return;let x=h.x,y=h.y,z=h.z;if(!breaking){x=Math.floor(h.x+h.n.x*.01);y=Math.floor(h.y+h.n.y*.01);z=Math.floor(h.z+h.n.z*.01);if(world.get(x,y,z)!=='air')return;const id=ITEMS[selected];if((inventory[id]||0)<=0)return;world.set(x,y,z,id);inventory[id]--}else{const id=world.get(x,y,z);if(id==='air')return;world.set(x,y,z,'air');if(inventory[id]!==undefined)inventory[id]++}chunks.rebuild()}
function bind(){canvas.addEventListener('click',()=>document.body.requestPointerLock());document.addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===document.body);document.addEventListener('mousemove',e=>{if(!locked)return;player.yaw-=e.movementX*.002;player.pitch-=e.movementY*.002;player.pitch=Math.max(-1.55,Math.min(1.55,player.pitch))});document.addEventListener('keydown',e=>{keys.add(e.code);if(e.code.startsWith('Digit')){selected=Math.min(ITEMS.length-1,Math.max(0,Number(e.code.slice(5))-1));renderHotbar(selected)}});document.addEventListener('keyup',e=>keys.delete(e.code));document.addEventListener('mousedown',e=>{if(!locked)return;e.preventDefault();if(e.button===0)edit(true);if(e.button===2)edit(false)});document.addEventListener('contextmenu',e=>e.preventDefault());document.querySelector('#newWorld').onclick=()=>{const s=document.querySelector('#seed').value;const seed=s===''?(Math.random()*0x7fffffff)|0:Number(s)|0;const w=createWorld(seed);w.player.x=.5;w.player.z=.5;w.player.y=w.heightAt(0,0)+1.01;initWorld(w,document.querySelector('#worldName').value.trim()||'My World')};document.querySelector('#loadWorld').onclick=async()=>{const n=document.querySelector('#worldName').value.trim()||'My World';const w=await loadWorld(n);if(w)initWorld(w,n);else status('No saved world with that name.')};document.querySelector('#exportWorld').onclick=()=>world&&downloadSave(worldName,world);document.querySelector('#importButton').onclick=()=>document.querySelector('#importWorld').click();document.querySelector('#importWorld').onchange=async e=>{const f=e.target.files[0];if(!f)return;initWorld(await readImport(f),f.name.replace(/\.json$/i,''));e.target.value=''};window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function tick(dt){if(!world)return;movePlayer(world,player,velocity,dt,keys);syncCamera(camera,player);const nowUnder=isUnderwater(world,camera);if(nowUnder!==underwater){underwater=nowUnder;const d=updateWaterView(scene,renderer,underwater);chunks.update(player.x,player.z,d);status(`Render distance: ${d} chunks${underwater?' · underwater':''}`)}else chunks.update(player.x,player.z,chunks.distance);world.time+=dt;autosave+=dt;if(autosave>8){autosave=0;savePlayer(world,player);saveWorld(worldName,world).catch(()=>{})}}
function animate(){requestAnimationFrame(animate);const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;tick(dt);renderer.render(scene,camera)}
async function start(){setupScene();atlas=await loadTexture();bind();renderHotbar(0);status(`Ready · default render distance ${DEFAULT_RENDER_DISTANCE}, underwater ${UNDERWATER_RENDER_DISTANCE}`);animate()}start().catch(e=>{console.error(e);status(`Startup error: ${e.message}`)});
