import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {BLOCKS,TILE,isOpaque} from './blocks.js';
import {CHUNK,HEIGHT} from './config.js';
import {inRenderDistance} from './world.js';
export function createRenderer(canvas){const renderer=new THREE.WebGLRenderer({canvas,antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;return renderer}
const faces=[{n:[0,0,1],v:[[0,0,1],[1,0,1],[1,1,1],[0,1,1]],d:'side'},{n:[0,0,-1],v:[[1,0,0],[0,0,0],[0,1,0],[1,1,0]],d:'side'},{n:[0,1,0],v:[[0,1,1],[1,1,1],[1,1,0],[0,1,0]],d:'top'},{n:[0,-1,0],v:[[0,0,0],[1,0,0],[1,0,1],[0,0,1]],d:'bottom'},{n:[1,0,0],v:[[1,0,1],[1,0,0],[1,1,0],[1,1,1]],d:'side'},{n:[-1,0,0],v:[[0,0,0],[0,0,1],[0,1,1],[0,1,0]],d:'side'}];
function addFace(a,f,x,y,z,uv){const i=a.p.length/3;for(const p of f.v){a.p.push(x+p[0],y+p[1],z+p[2]);a.n.push(...f.n);a.u.push(p[0]?uv[2]:uv[0],p[1]?uv[3]:uv[1])}a.idx.push(i,i+1,i+2,i,i+2,i+3)}
export function buildChunkMesh(world,cx,cz,atlas){const a=new Map();const minX=cx*CHUNK,minZ=cz*CHUNK;for(let x=minX;x<minX+CHUNK;x++)for(let z=minZ;z<minZ+CHUNK;z++)for(let y=0;y<HEIGHT;y++){const id=world.get(x,y,z);if(id==='air')continue;const def=BLOCKS[id];if(!def)continue;for(const f of faces){const nx=x+f.n[0],ny=y+f.n[1],nz=z+f.n[2],nid=world.get(nx,ny,nz);if(def.water){if(nid==='water')continue;if(f.d==='bottom'&&nid!=='air')continue}else if(isOpaque(id)&&isOpaque(nid))continue;else if(!isOpaque(id)&&nid===id)continue;let m=a.get(id);if(!m){m={p:[],n:[],u:[],idx:[]};a.set(id,m)}const tile=TILE[id]?.[f.d]??0;const tx=tile%16,ty=Math.floor(tile/16),s=1/16,r=1/4;addFace(m,f,x,y,z,[tx*s,1-(ty+1)*r,(tx+1)*s,1-ty*r])}}
const group=new THREE.Group();for(const [id,d] of a){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(d.p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(d.n,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(d.u,2));g.setIndex(d.idx);g.computeBoundingSphere();const def=BLOCKS[id];const mat=new THREE.MeshLambertMaterial({map:atlas,transparent:!!def.transparent,opacity:def.opacity??1,depthWrite:!def.transparent,side:THREE.FrontSide});if(def.emissive){mat.emissive=new THREE.Color(0xffcc44);mat.emissiveIntensity=1}const mesh=new THREE.Mesh(g,mat);mesh.userData={blockType:id,chunk:[cx,cz]};group.add(mesh)}group.userData.chunk=[cx,cz];return group}
export function rebuildVisible(world,scene,chunkMeshes,pcx,pcz,renderDistance,atlas){for(const [ck,g] of chunkMeshes){const [cx,cz]=ck.split(',').map(Number);if(!inRenderDistance(cx,cz,pcx,pcz,renderDistance)){scene.remove(g);chunkMeshes.delete(ck)}}for(const ck of world.generatedChunks){const [cx,cz]=ck.split(',').map(Number);if(!inRenderDistance(cx,cz,pcx,pcz,renderDistance)||chunkMeshes.has(ck))continue;const g=buildChunkMesh(world,cx,cz,atlas);chunkMeshes.set(ck,g);scene.add(g)}}
